# nodejs ?? npm ???
# version ???
FROM node:24-alpine3.21

# make new folder
WORKDIR /app/web

# init project, we have to have code
# code
# copy from(folder of your pc) to (folder of docker)
# COPY . /app/web

# install lib
# RUN npm i

# run app
# CMD ["npm", "run", "dev"]